# Generated by Django 5.0.6 on 2024-08-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='tipo_telefono',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Privado', 'Privado'), ('Trabajo', 'Trabajo')], max_length=20),
        ),
    ]
